### ISSUE TITLE
Validate transparent backgrounds after external css files download

### ISSUE THREAD

**Issue by pavel-agarkov** [pavel-agarkov/Midnight-Lizard#42]
https://examine.com/supplements/polygala-tenuifolia/
// https://v7-examinecdn.scdn5.secure.raxcdn.com/assets/build/css/styles-bundle.min.css?v=v7.55-19-ga44fbb8
.site--wrapper .bg-info {
    border-radius: 3px;
    background-color: #ebfcff;
    border: solid 1px #d1eff4;
}

**Comment by widget-** [comment]
Thanks for opening an issue.

I'm having trouble figuring their site out, but it looks like the loader script is in an async script tag, which waits until onContentLoaded to begin to download and inject the global stylesheet. I have no idea why they would do that but whatever.

If I were to guess, adding `characterData: true` to https://github.com/pavel-agarkov/Midnight-Lizard/blob/0bd9c9a60742f0afee452911fdf6cf4184ecbb5d/ts/ContentScript/DocumentObserver.ts#L28 so that it listens for `innerHTML` changes might fix it. There would be a small performance hit, but I don't think `head` elements usually change often enough to worry.
