### ISSUE TITLE
New logo for Midnight-Lizard

### ISSUE THREAD

**Issue by ihtiht** [pavel-agarkov/Midnight-Lizard#55]
Hi, I think the current logo is irrelevant to Midnight-Lizard and I designed a new logo. I hope you liked it. 

If you want, I can give you your logo files.

![untitled-2](https://user-images.githubusercontent.com/36369736/38689533-98b9944e-3e84-11e8-940b-3b8ec8fdf0a5.png)

![ml](https://user-images.githubusercontent.com/36369736/38689547-9dad5e04-3e84-11e8-98cc-1a01fe16f9c6.png)

**Comment by pavel-agarkov** [comment]
Hi @ihtiht 
Yes, it might be seen as irrelevant the same as the title Midnight Lizard.
But there is a logic 😄
### So why Midnight Lizard?
1) Midnight - because it is related to night mode
2) Lizard - many lizards can change colors

### Why this logo?
1) There is a lizard on it
2) The logo can be written with symbols like this: {$}. This symbols represent Midnight Lizard's relation to JavaScript since it changes styles with this language. Also $ looks like S from Style so it like JavaScript Styling.

All of this are not that simple and understandable but I made it on purpose. I didn't want my extension to look the same as all others which have similar names and logos. Yes it is easier to find them but you won't remember them. And you won't be able to find them second time without a direct link because there are too many of them like "Night mode", "Night mode pro", "Night mode extra", "Night mode plus" etc... and all with the same logo like  🌓

BTW: your icon looks good! But from my perspective it looks overly standard when I want to be unique.
Probably I' wrong 😅

**Comment by ihtiht** [comment]
voow ! Different and unique. I never thought you'd come up with such an idea. You're right. I liked the idea that the lizard can change the color. Sorry I just wanted to make a contribution. Good work !

**Comment by pavel-agarkov** [comment]
Closing this, but I would love to see some other contributions.
I'm not experienced in this area and I don't know how it should be organized.
